import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';
// We instantiate a new client for each call to ensure fresh state if needed, 
// but keeping a singleton is also fine. 
// However, per instructions, we must assume API_KEY is present.

export const editImageWithGemini = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Remove data URL prefix if present
  const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: `${prompt}. Ensure the face remains unchanged and identity is preserved. Output high quality photorealistic image.`,
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64,
            },
          },
        ],
      },
      config: {
        // Not using systemInstruction as it's sometimes restrictive for image editing in flash-image
        // Using topK/topP defaults
      }
    });

    // Extract image from response
    // The model might return text + image or just image. We look for inlineData.
    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
